LAB09 Feature/cde7
eviplabs/start pull request #19
Opened 2021-03-11 11:01 UTC by gabor9977

A feladatot mérőtérsammal csináltuk:
Tibély Orsolya Sára CIF2LT
Hartyányi Gábor D3XP4L

2021-03-12 18:15 UTC, zszabo775 requested changes
readme.md-t kérném kitölteni, egyébként rendben.

2021-03-17 21:29 UTC, gabor9977 commented
kitöltöttuk a kért readme-t. Feltölthetjük a jegyzokonyvet?

2021-03-17 21:33 UTC, zszabo775 commented
Persze

gabor9977 ***@***.***> ezt írta (2021. márc. 17. 22:29):

kitöltöttuk a kért readme-t. Feltölthetjük a jegyzokonyvet?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/eviplabs/start/pull/19#issuecomment-801455488>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATFH3LSAWWFV4QXTFTFTLJLTEENL5ANCNFSM4ZABWSZQ>.

2021-03-19 09:45 UTC, zszabo775 approved these changes

2021-09-15 12:10 UTC, closed without merging